/** Approved editable interest taxonomy (IC-02D). */

export const VOLUNTEER_INTEREST_TAXONOMY = [
  { key: "county_organizing", label: "County organizing" },
  { key: "voter_registration", label: "Voter registration" },
  { key: "canvassing", label: "Canvassing" },
  { key: "phone_banking", label: "Phone banking" },
  { key: "texting", label: "Texting" },
  { key: "events", label: "Events" },
  { key: "youth_campus", label: "Youth / campus" },
  { key: "communications", label: "Communications" },
  { key: "writing", label: "Writing" },
  { key: "graphics", label: "Graphics" },
  { key: "social_media", label: "Social media" },
  { key: "photo_video", label: "Photography / video" },
  { key: "press", label: "Press" },
  { key: "fundraising", label: "Fundraising" },
  { key: "data_entry", label: "Data entry" },
  { key: "research", label: "Research" },
  { key: "driving", label: "Driving" },
  { key: "lodging_hosting", label: "Lodging / hosting" },
  { key: "food_hospitality", label: "Food / hospitality" },
  { key: "materials", label: "Materials" },
  { key: "accessibility", label: "Accessibility" },
  { key: "training", label: "Training" },
  { key: "leadership", label: "Leadership" },
] as const;

export const VOLUNTEER_TRAINING_CATALOG = [
  { key: "campaign_orientation", title: "Campaign orientation" },
  { key: "voter_registration", title: "Voter-registration program" },
  { key: "canvassing", title: "Canvassing" },
  { key: "phone_banking", title: "Phone banking" },
  { key: "texting", title: "Texting" },
  { key: "event_support", title: "Event support" },
  { key: "county_leadership", title: "County leadership" },
  { key: "data_privacy", title: "Data / privacy" },
  { key: "communications", title: "Communications" },
  { key: "logistics", title: "Logistics" },
  { key: "safety_incident", title: "Safety and incident escalation" },
] as const;

export const DRILL_DOWN_LINKS = [
  { href: "/system/volunteers/people", label: "People" },
  { href: "/system/volunteers/intake", label: "Intake" },
  { href: "/system/volunteers/placement", label: "Placement" },
  { href: "/system/volunteers/opportunities", label: "Opportunities" },
  { href: "/system/volunteers/assignments", label: "Assignments" },
  { href: "/system/volunteers/shifts", label: "Shifts" },
  { href: "/system/volunteers/training", label: "Training" },
  { href: "/system/volunteers/skills", label: "Skills" },
  { href: "/system/volunteers/availability", label: "Availability" },
  { href: "/system/volunteers/retention", label: "Retention" },
  { href: "/system/volunteers/leadership", label: "Leadership" },
  { href: "/system/volunteers/counties", label: "Counties" },
  { href: "/system/volunteers/clusters", label: "Clusters" },
  { href: "/system/volunteers/voter-engagement", label: "Voter engagement" },
  { href: "/system/volunteers/youth", label: "College & youth" },
  { href: "/system/volunteers/events", label: "Events & actions" },
  { href: "/system/volunteers/calendar", label: "Calendar" },
  { href: "/system/volunteers/reports", label: "Reports" },
  { href: "/system/volunteers/policy", label: "Policy" },
] as const;
