/** Only these names may be imported from RedDirt fallback files. */
export const APPROVED_REDDIRT_FALLBACK_KEYS = [
  "DATABASE_URL",
  "DIRECT_URL",
  "OPENAI_API_KEY",
  "NEXT_PUBLIC_SUPABASE_URL",
  "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
  "APP_SESSION_SECRET",
] as const;

export type ApprovedRedDirtFallbackKey =
  (typeof APPROVED_REDDIRT_FALLBACK_KEYS)[number];

export const PUBLIC_ENV_KEYS = [
  "NEXT_PUBLIC_APP_NAME",
  "NEXT_PUBLIC_APP_URL",
  "NEXT_PUBLIC_CAMPAIGN_TIMEZONE",
  "NEXT_PUBLIC_ELECTION_DATE",
  "NEXT_PUBLIC_SUPABASE_URL",
  "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY",
] as const;

export const SERVER_ONLY_ENV_KEYS = [
  "DATABASE_URL",
  "DIRECT_URL",
  "OPENAI_API_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
  "APP_SESSION_SECRET",
  "INTERNAL_API_SECRET",
  "LOG_LEVEL",
  "ENV_FALLBACK_TO_REDDIRT",
  /** Secret Google private iCal address — never expose value; presence only in diagnostics. */
  "KCCC_GOOGLE_CALENDAR_ICAL_URL",
  "KCCC_GOOGLE_CLIENT_ID",
  "KCCC_GOOGLE_CLIENT_SECRET",
  "KCCC_GOOGLE_CALENDAR_ID",
  "KCCC_GOOGLE_TOKEN_ENCRYPTION_KEY",
  "KCCC_GOOGLE_OAUTH_REDIRECT_URI",
  "KCCC_GOOGLE_MAPS_ROUTES_API_KEY",
  "KCCC_GOOGLE_SYNC_ENABLED",
  "KCCC_GOOGLE_ROUTES_ENABLED",
  "KCCC_GOOGLE_HISTORY_START",
] as const;

export const FORBIDDEN_PUBLIC_PREFIX_KEYS = [
  "NEXT_PUBLIC_DATABASE_URL",
  "NEXT_PUBLIC_OPENAI_API_KEY",
  "NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY",
  "NEXT_PUBLIC_DIRECT_URL",
  "NEXT_PUBLIC_APP_SESSION_SECRET",
  "NEXT_PUBLIC_INTERNAL_API_SECRET",
  "NEXT_PUBLIC_KCCC_GOOGLE_CALENDAR_ICAL_URL",
] as const;
