/** Only these names may be imported from RedDirt fallback files. */
export const APPROVED_REDDIRT_FALLBACK_KEYS = [
  "DATABASE_URL",
  "DIRECT_URL",
  "OPENAI_API_KEY",
  "NEXT_PUBLIC_SUPABASE_URL",
  "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
] as const;

export type ApprovedRedDirtFallbackKey =
  (typeof APPROVED_REDDIRT_FALLBACK_KEYS)[number];

export const PUBLIC_ENV_KEYS = [
  "NEXT_PUBLIC_APP_NAME",
  "NEXT_PUBLIC_APP_URL",
  "NEXT_PUBLIC_CAMPAIGN_TIMEZONE",
  "NEXT_PUBLIC_ELECTION_DATE",
  "NEXT_PUBLIC_SUPABASE_URL",
  "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY",
] as const;

export const SERVER_ONLY_ENV_KEYS = [
  "DATABASE_URL",
  "DIRECT_URL",
  "OPENAI_API_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
  "APP_SESSION_SECRET",
  "INTERNAL_API_SECRET",
  "LOG_LEVEL",
  "ENV_FALLBACK_TO_REDDIRT",
] as const;

export const FORBIDDEN_PUBLIC_PREFIX_KEYS = [
  "NEXT_PUBLIC_DATABASE_URL",
  "NEXT_PUBLIC_OPENAI_API_KEY",
  "NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY",
  "NEXT_PUBLIC_DIRECT_URL",
  "NEXT_PUBLIC_APP_SESSION_SECRET",
  "NEXT_PUBLIC_INTERNAL_API_SECRET",
] as const;
