/** All 75 Arkansas counties for dropdown entry. */
export const ARKANSAS_COUNTIES = [
  "Arkansas",
  "Ashley",
  "Baxter",
  "Benton",
  "Boone",
  "Bradley",
  "Calhoun",
  "Carroll",
  "Chicot",
  "Clark",
  "Clay",
  "Cleburne",
  "Cleveland",
  "Columbia",
  "Conway",
  "Craighead",
  "Crawford",
  "Crittenden",
  "Cross",
  "Dallas",
  "Desha",
  "Drew",
  "Faulkner",
  "Franklin",
  "Fulton",
  "Garland",
  "Grant",
  "Greene",
  "Hempstead",
  "Hot Spring",
  "Howard",
  "Independence",
  "Izard",
  "Jackson",
  "Jefferson",
  "Johnson",
  "Lafayette",
  "Lawrence",
  "Lee",
  "Lincoln",
  "Little River",
  "Logan",
  "Lonoke",
  "Madison",
  "Marion",
  "Miller",
  "Mississippi",
  "Monroe",
  "Montgomery",
  "Nevada",
  "Newton",
  "Ouachita",
  "Perry",
  "Phillips",
  "Pike",
  "Poinsett",
  "Polk",
  "Pope",
  "Prairie",
  "Pulaski",
  "Randolph",
  "St. Francis",
  "Saline",
  "Scott",
  "Searcy",
  "Sebastian",
  "Sevier",
  "Sharp",
  "Stone",
  "Union",
  "Van Buren",
  "Washington",
  "White",
  "Woodruff",
  "Yell",
] as const;

export const ARKANSAS_REGIONS = [
  "Central Arkansas",
  "Northwest Arkansas",
  "Northeast Arkansas",
  "Southwest Arkansas",
  "Southeast Arkansas",
  "River Valley",
  "Delta",
] as const;

export const PRIMARY_CALENDARS = [
  "Candidate Schedule",
  "Travel",
  "Fundraising",
  "Public Events",
  "Internal Meetings",
  "Communications",
  "Social Media",
  "Press and Media",
  "Field Organizing",
  "County Activity",
  "Volunteer Operations",
  "Compliance",
  "Staff Work Schedule",
  "Debate Preparation",
  "Surrogate Activity",
  "Protected Personal Time",
  "Other",
] as const;

export const EVENT_TYPES_BY_CALENDAR: Record<string, string[]> = {
  "Public Events": [
    "Festival",
    "Parade",
    "Candidate forum",
    "Debate",
    "Town hall",
    "Community meeting",
    "Speaking engagement",
    "Meet and greet",
    "County fair",
    "Farm visit",
    "Business visit",
    "Church or faith event",
    "Civic-club meeting",
    "University or college event",
    "School event",
    "Conference",
    "Reception",
    "Rally",
    "Door-knocking launch",
    "Volunteer event",
    "Other",
  ],
  Fundraising: [
    "Fundraiser",
    "Call time",
    "Donor meeting",
    "Finance committee meeting",
    "Host meeting",
    "Fundraising follow-up",
    "Sponsorship deadline",
    "Contribution-report deadline",
    "Other",
  ],
  Communications: [
    "Press release",
    "Email",
    "Text campaign",
    "Website update",
    "Speech",
    "Talking points",
    "Media preparation",
    "Rapid response",
    "Newsletter",
    "Advertisement",
    "Other",
  ],
  Travel: ["Travel block", "Drive", "Flight", "Lodging", "Other"],
  "Protected Personal Time": ["Protected personal block", "Other"],
  default: [
    "Meeting",
    "Call",
    "Appearance",
    "Work block",
    "Other",
  ],
};

export function eventTypesForCalendar(calendar: string): string[] {
  return EVENT_TYPES_BY_CALENDAR[calendar] ?? EVENT_TYPES_BY_CALENDAR.default;
}
