export const CURRENT_STEP_ID = "KCCC-OPERATOR-USABILITY-PASS-1";
export const CURRENT_STEP_NUMBER = 11;
/** Calendar recovery — communications frozen; primary track returns to calendar. */
export const CALENDAR_RECOVERY_BUILD_ID =
  "KCCC-CALENDAR-RECOVERY-RETURN-TO-CORE-1.0";
export const CALENDAR_PRIMARY_TRACK_STATUS = "ACTIVE";
export const COMMUNICATIONS_OS_TRACK_STATUS = "FROZEN";
export const LG1_CONTROLLED_LIVE_TEST_STATUS = "PAUSED";
export const STEP_8_CLOSEOUT_BUILD_ID = "KCCC-EA-8-SECURITY-CLOSEOUT-1.0";
export const STEP_8_CLOSEOUT_STATUS = "COMPLETE";
export const STEP_9_CANONICAL_EVENT_BUILD_ID =
  "KCCC-EA-9-CANONICAL-CALENDAR-DATA-MODEL-1.0";
export const STEP_9_CANONICAL_EVENT_STATUS = "COMPLETE";
export const STEP_10_OPERATING_VIEWS_BUILD_ID =
  "KCCC-EA-10-CALENDAR-OPERATING-VIEWS-1.0";
export const STEP_10_OPERATING_VIEWS_STATUS = "COMPLETE";
export const STEP_11_EVENT_EDITING_BUILD_ID =
  "KCCC-EA-11-EVENT-CREATION-EDITING-1.0";
export const STEP_11_EVENT_EDITING_STATUS = "COMPLETE";
/** Human operator validation — blocks Step 12 until reviewed. */
export const OPERATOR_USABILITY_PASS_ID = "KCCC-OPERATOR-USABILITY-PASS-1";
export const OPERATOR_USABILITY_PASS_STATUS = "OPEN";
export const OPERATOR_USABILITY_PASS_DOC =
  "develop_notes/KCCC_OPERATOR_USABILITY_PASS_1.md";
export const OPERATOR_OBSERVATION_CADENCE_DOC =
  "develop_notes/KCCC_OPERATOR_OBSERVATION_CADENCE.md";
export const OPERATOR_USABILITY_SYNTHESIS_DOC =
  "develop_notes/KCCC_OPERATOR_USABILITY_SYNTHESIS_1.md";
/** Steps 8–11 shipped; Steps 12–13 remain gated by Usability Synthesis. */
export const CALENDAR_FOUNDATION_V1_STATUS = "BUILD_COMPLETE";
export const CALENDAR_FOUNDATION_V1_GATE = "OPERATOR_OBSERVATION_PASS_1";
/**
 * Calendar Completion program (CC-01…CC-12) — locked 2026-07-21.
 * Primary engineering track while unrelated campaign expansion is paused.
 * CC-05 authorized by Kelly waiver ADR-090 (2026-07-22). CC-06 authorized by
 * Kelly ADR-092 (2026-07-22) and now COMPLETE (calendar slice — minimum
 * TIME_OVERLAP/AVAILABILITY_VIOLATION/BUFFER_CONFLICT/TRAVEL_INFEASIBLE
 * detectors). CC-07 remains DESIGN ONLY — not implemented.
 * Usability Synthesis remains EMPTY — not completed by CC-05 or CC-06.
 */
export const CALENDAR_COMPLETION_PROGRAM_ID =
  "KCCC-CALENDAR-COMPLETION-PROGRAM-1.0";
export const CALENDAR_COMPLETION_PROGRAM_STATUS = "LOCKED";
export const CALENDAR_COMPLETION_BASELINE_COMMIT = "9c89012";
export const CALENDAR_COMPLETION_NEXT = "CC-07-DESIGN-ONLY";
export const CALENDAR_COMPLETION_NEXT_BUILD_ID =
  "KCCC-CC-06-CONFLICT-ENGINE-1.0";
export const CALENDAR_COMPLETION_PROGRAM_DOC =
  "develop_notes/KCCC_CALENDAR_COMPLETION_PROGRAM.md";
export const CALENDAR_COMPLETION_ASSESSMENT_DOC =
  "develop_notes/KCCC_CALENDAR_COMPLETION_ASSESSMENT_BURT_2026-07-21.md";
export const CC_01_BUILD_ID = "KCCC-CC-01-IMPORT-APPROVAL-CANONICAL-APPLY-1.0";
export const CC_01_STATUS = "COMPLETE";
export const CC_02_BUILD_ID =
  "KCCC-CC-02-CALENDAR-INTEGRITY-PROVENANCE-CONSOLE-1.0";
export const CC_02_STATUS = "COMPLETE";
export const CC_03_BUILD_ID =
  "KCCC-CC-03-TIMEZONE-ALLDAY-OVERNIGHT-HARDENING-1.0";
export const CC_03_STATUS = "COMPLETE";
export const CC_04_BUILD_ID =
  "KCCC-CC-04-RECURRENCE-OCCURRENCE-EXCEPTIONS-1.0";
export const CC_04_STATUS = "COMPLETE";
export const CC_05_BUILD_ID =
  "KCCC-CC-05-STANDING-AVAILABILITY-INPUTS-1.0";
export const CC_05_STATUS = "COMPLETE";
export const CC_05_SHIP_COMMIT = "46a72c3";
export const CC_05_SHIP_DEPLOY_ID = "6a60efa8f25804bc9b16f3f3";
export const CC_05_WAIVER_ADR = "ADR-090";
export const CC_05_WAIVER_DOC =
  "develop_notes/KCCC_CC_05_WAIVER_KELLY_2026-07-22.md";
export const CC_06_BUILD_ID = "KCCC-CC-06-CONFLICT-ENGINE-1.0";
export const CC_06_STATUS = "COMPLETE";
export const CC_06_AUTHORIZATION_ADR = "ADR-092";
export const CC_06_AUTHORIZATION_DOC =
  "develop_notes/KCCC_CC_06_AUTHORIZATION_KELLY_2026-07-22.md";
export const CC_06_CONFLICT_ENGINE_DOC =
  "develop_notes/KCCC_CC_06_CONFLICT_ENGINE.md";
export const CC_06_CONFLICT_ENGINE_ROLLBACK_DOC =
  "develop_notes/KCCC_CC_06_CONFLICT_ENGINE_ROLLBACK.md";
export const CALENDAR_CONFLICT_DOCTRINE_DOC =
  "develop_notes/KCCC_CALENDAR_CONFLICT_DOCTRINE.md";
export const CALENDAR_CONFLICT_OPERATOR_GUIDE_DOC =
  "develop_notes/KCCC_CALENDAR_CONFLICT_OPERATOR_GUIDE.md";
export const CC_07_STATUS = "COMPLETE";
export const CC_07_BUILD_ID =
  "KCCC-CC-07-UNIFIED-SEARCH-FILTERS-SAVED-VIEWS-1.0";
export const CC_07_DESIGN_DOC =
  "develop_notes/KCCC_CC_07_UNIFIED_SEARCH_FILTERS_SAVED_VIEWS_DESIGN.md";
export const CC_07_AUTHORIZATION_ADR = "ADR-095";
export const CC_07_AUTHORIZATION_DOC =
  "develop_notes/KCCC_CC_07_AUTHORIZATION_KELLY_2026-07-22.md";
export const STANDING_KELLY_EXECUTION_ADR = "ADR-094";
export const STANDING_KELLY_EXECUTION_DOC =
  "develop_notes/KCCC_STANDING_KELLY_EXECUTION_AUTHORIZATION_2026-07-22.md";
export const CALENDAR_QUERY_SCHEMA_VERSION = 1;
export const POST_CC05_DIRECTION_ADR = "ADR-091";
export const POST_CC05_DIRECTION_DOC =
  "develop_notes/KCCC_POST_CC05_USABILITY_PASS_DIRECTION.md";
/**
 * Phase Two vision locked (ADR-093).
 * Protected: CC-07→12 → usability/AI-quality gate → IC auth → IC-01…IC-12.
 * During CC-07…CC-12: clean extension points only; no hidden Phase Two features.
 */
export const PHASE_TWO_PROGRAM_ID =
  "KCCC-PHASE-TWO-INTELLIGENT-STATEWIDE-CAMPAIGN-CALENDAR-1.0";
export const PHASE_TWO_PROGRAM_STATUS = "VISION_LOCKED_NOT_AUTHORIZED";
export const PHASE_TWO_VISION_ADR = "ADR-093";
export const PHASE_TWO_VISION_DOC =
  "develop_notes/KCCC_PHASE_TWO_VISION_LOCK_KELLY_2026-07-22.md";
export const PHASE_TWO_PROGRAM_DOC =
  "develop_notes/KCCC_PHASE_TWO_INTELLIGENT_STATEWIDE_CAMPAIGN_CALENDAR.md";
export const PHASE_TWO_PROTECTED_SEQUENCE =
  "CC-07→CC-08→CC-09→CC-10→CC-11→CC-12→usability_ai_quality_gate→IC_phase_authorization";
export const PHASE_TWO_AI_PRINCIPLE =
  "DETERMINISTIC_FACTS_AI_EXPLAINS_WITHIN_CONFIRMATION_BOUNDARIES";
export const AUTHORITATIVE_TIP_COMMIT = "68d6476";
export const POSTURE_LOCK_COMMIT = "203bfe3";
export const UNRELATED_CAMPAIGN_EXPANSION_STATUS = "PAUSED";
export const STEP_12_AVAILABILITY_STATUS = "COMPLETE_CC05";
/**
 * Conflict Engine (CC-06) authorized by Kelly ADR-092; calendar slice
 * (TIME_OVERLAP, AVAILABILITY_VIOLATION, BUFFER_CONFLICT, TRAVEL_INFEASIBLE)
 * is implemented. Remaining EA-13 conflict types (participant/venue/
 * priority/prep/followup/resource) remain design-only. Never auto-mutate.
 */
export const STEP_13_CONFLICT_ENGINE_STATUS = "IMPLEMENTED_CC06_CALENDAR_SLICE";
export const STEP_13_CONFLICT_ENGINE_DOC =
  "develop_notes/KCCC_EA_13_CONFLICT_ENGINE_ARCHITECTURE.md";
/** Step 13 is the first Intelligence Layer slice; Operational Layer ends at Step 12. */
export const ARCHITECTURE_LAYERS_DOC =
  "develop_notes/KCCC_OPERATIONAL_VS_INTELLIGENCE_LAYERS.md";
export const CAMPAIGN_OS_DOCTRINE_1_DOC =
  "develop_notes/KCCC_CAMPAIGN_OS_DOCTRINE_1.md";
export const CAMPAIGN_OS_DOCTRINE_1 =
  "OPERATOR_DEFINES_REALITY_SYSTEM_INTERPRETS_REALITY";
export const CAMPAIGN_OS_BASELINE_VERSION = "1.0";
export const CAMPAIGN_OS_BASELINE_STATUS = "FROZEN";
export const CAMPAIGN_OS_BASELINE_IMMUTABLE = true;
export const CAMPAIGN_OS_BASELINE_DOC =
  "develop_notes/KCCC_CAMPAIGN_OS_BASELINE_1_0_FROZEN.md";
export const CAMPAIGN_OS_NEXT_BASELINE = "1.1";
export const CAMPAIGN_OS_NEXT_BASELINE_STATUS =
  "PENDING_OPERATOR_OBSERVATION_EVIDENCE";
export const CAMPAIGN_OS_POSTURE = "READY_FOR_OPERATOR_OBSERVATION";
export const ENGINEERING_CHAPTER_CLOSEOUT_DOC =
  "develop_notes/KCCC_ENGINEERING_CHAPTER_CLOSEOUT_BASELINE_1_0.md";
export const ENGINEERING_CHAPTER_1_STATUS = "CLOSED";
export const ENGINEERING_CHAPTER_1_TITLE =
  "Calendar Foundation to Campaign OS Baseline 1.0";
export const ENGINEERING_CHAPTER_1_CLOSED_DOC =
  "develop_notes/KCCC_ENGINEERING_CHAPTER_1_CLOSED.md";
export const CAMPAIGN_OS_PHASE = "EVIDENCE_ACQUISITION";
export const NEXT_AUTHORITY = "OPERATOR_EVIDENCE";
export const GOVERNING_DEVELOPMENT_CYCLE =
  "OBSERVE_RECORD_SYNTHESIZE_DECIDE_BUILD_OBSERVE_AGAIN";
export const CHAPTER_2_SUCCESS_CRITERION =
  "HOW_DO_CAMPAIGN_OPERATORS_NATURALLY_ORGANIZE_THEIR_DAY";
export const NEXT_ENGINEERING_DECISION_SOURCE =
  "OPERATOR_OBSERVATION_EVIDENCE_ONLY";
export const POST_OBSERVATION_REVIEW_STAGES =
  "EVIDENCE_PATTERNS_BASELINE_1_1_REQUIREMENTS_AUTHORIZATION";
export const FURTHER_ARCHITECTURE_DOCTRINE_STATUS =
  "HOLD_UNTIL_OPERATOR_OBSERVATION_PASS_1";
export const SCHEDULE_MUTATION_GOVERNING_RULE =
  "DETECT_EXPLAIN_RECOMMEND_SIMULATE_NEVER_AUTO_MUTATE";
/**
 * CC-07…CC-09 complete under standing execution ADR-094.
 * CC-10 is not absorbed by this build. Synthesis remains EMPTY (ADR-091).
 * Phase Two IC-01…IC-12 is VISION LOCKED (ADR-093) — design during CC-07…CC-12
 * is allowed; implementation waits until after CC-12.
 */
export const CC_08_STATUS = "COMPLETE";
export const CC_08_BUILD_ID =
  "KCCC-CC-08-ADVANCED-DAY-WEEK-SCHEDULING-WORKSPACE-1.0";
export const CC_08_AUTHORIZATION_ADR = "ADR-096";
export const CC_08_AUTHORIZATION_DOC =
  "develop_notes/KCCC_CC_08_AUTHORIZATION_KELLY_2026-07-22.md";
export const CC_08_DESIGN_NOTE =
  "Advanced Day/Week Scheduling Workspace — grid-first; no drag/resize";
export const CC_08_IMPL_DOC =
  "develop_notes/KCCC_CC_08_ADVANCED_DAY_WEEK_SCHEDULING_WORKSPACE.md";
export const CC_08_ROLLBACK_DOC =
  "develop_notes/KCCC_CC_08_ADVANCED_DAY_WEEK_SCHEDULING_WORKSPACE_ROLLBACK.md";
export const CALENDAR_SCHEDULING_WORKSPACE_DOCTRINE_DOC =
  "develop_notes/KCCC_CALENDAR_SCHEDULING_WORKSPACE_DOCTRINE.md";
export const CALENDAR_DAY_WEEK_OPERATOR_GUIDE_DOC =
  "develop_notes/KCCC_CALENDAR_DAY_WEEK_OPERATOR_GUIDE.md";
export const CC_07_SHIP_COMMIT = "a630c8c";
export const CC_07_SHIP_DEPLOY_ID = "6a61167b80d9714ef4541631";
export const CC_08_SHIP_COMMIT = "7486aa9";
export const CC_08_SHIP_DEPLOY_ID = "6a611dc19547e64f0fa7874d";
export const CC_08_TIP_COMMIT = "e1ddaa7";
export const CC_08_TIP_DEPLOY_ID = "6a612111e81d923c5e6c58ca";
export const NEXT_AUTHORIZED_BUILD = "CC_10_NOT_AUTHORIZED";
export const CC_09_STATUS = "COMPLETE";
export const CC_09_BUILD_ID =
  "KCCC-CC-09-BULK-OPERATIONS-ARCHIVE-RESTORE-RECOVERY-1.0";
export const CC_09_AUTHORIZATION_ADR = "ADR-097";
export const CC_09_AUTHORIZATION_DOC =
  "develop_notes/KCCC_CC_09_AUTHORIZATION_KELLY_2026-07-22.md";
export const CC_09_IMPL_DOC =
  "develop_notes/KCCC_CC_09_BULK_OPERATIONS_ARCHIVE_RESTORE_RECOVERY.md";
export const CC_09_ROLLBACK_DOC =
  "develop_notes/KCCC_CC_09_BULK_OPERATIONS_ARCHIVE_RESTORE_RECOVERY_ROLLBACK.md";
export const CALENDAR_BULK_OPERATIONS_DOCTRINE_DOC =
  "develop_notes/KCCC_CALENDAR_BULK_OPERATIONS_DOCTRINE.md";
export const CALENDAR_BULK_OPERATIONS_OPERATOR_GUIDE_DOC =
  "develop_notes/KCCC_CALENDAR_BULK_OPERATIONS_OPERATOR_GUIDE.md";
export const CC_10_STATUS = "NOT_AUTHORIZED";
export const CC_07_IMPL_DOC =
  "develop_notes/KCCC_CC_07_UNIFIED_SEARCH_FILTERS_SAVED_VIEWS.md";
export const CC_07_ROLLBACK_DOC =
  "develop_notes/KCCC_CC_07_UNIFIED_SEARCH_FILTERS_SAVED_VIEWS_ROLLBACK.md";
export const CALENDAR_SEARCH_FILTER_DOCTRINE_DOC =
  "develop_notes/KCCC_CALENDAR_SEARCH_FILTER_DOCTRINE.md";
export const CALENDAR_SAVED_VIEWS_OPERATOR_GUIDE_DOC =
  "develop_notes/KCCC_CALENDAR_SAVED_VIEWS_OPERATOR_GUIDE.md";
export const CALENDAR_ROADMAP_DOC =
  "develop_notes/KCCC_CALENDAR_25_STEP_MASTER_ROADMAP.md";
/** Prisma model name — the only top-level Event entity. */
export const CANONICAL_EVENT_PRISMA_MODEL = "Event";
export const ARCHITECTURE_VERSION = "1.0";
export const ARCHITECTURE_STATUS = "HISTORICAL_BASELINE_PERMANENTLY_CLOSED";
export const ARCHITECTURE_LIFECYCLE = "COMPLETE";
export const PROJECT_STATE = "ARCHITECTURE_REVIEW";
export const IMPLEMENTATION_STATUS = "NOT_AUTHORIZED";
export const PHASE_3_EXIT_REVIEW_STATUS = "TRUST_MODEL_PASS_WITH_CONDITIONS";
export const PHASE_3_BUILD_DESIGN_ID = "KCCC_PHASE_03_BUILD_DESIGN";
export const PHASE_3_TRUST_MODEL_STATUS = "PASS_WITH_CONDITIONS";
export const PHASE_3_DRAFTING_PAUSED = true;
export const ENGINEERING_TRACK_A_ID = "KCCC-ENG-TRACK-A-CALENDAR-EXPERIENCE";
export const ENGINEERING_TRACK_A_STATUS = "ACTIVE";
export const CALENDAR_EXPERIENCE_PASS = "version-1-engineering-complete";
export const CALENDAR_EXPERIENCE_REVIEW_STATUS = "PASS";
export const CALENDAR_EXPERIENCE_VERSION = "1";
export const CALENDAR_EXPERIENCE_V1_STATUS = "ENGINEERING_COMPLETE";
export const CALENDAR_EXPERIENCE_V1_FEATURE_COMPLETE_PERMANENT = true;
export const V1_FEATURE_FREEZE_STATUS = "ACTIVE";
export const V1_FEATURE_FREEZE_ID = "KCCC-V1-FEATURE-FREEZE";
export const PLATFORM_STABILIZATION_STATUS = "ACTIVE";
export const FEATURE_DEVELOPMENT_STATUS = "FROZEN";
export const PROGRAM_CHARTER_STATUS = "ACTIVE";
export const PROGRAM_CHARTER_ID = "KCCC-PROGRAM-CHARTER";
export const GOVERNANCE_DESIGN_STATUS = "COMPLETE";
export const GOVERNANCE_EXECUTION_STATUS = "ACTIVE";
export const GOVERNANCE_EXECUTION_ID = "KCCC-GOVERNANCE-EXECUTION";
export const EXECUTION_DISCIPLINE_STATUS = "BEGINNING";
export const RELEASE_CONSTITUTION_STATUS = "ACTIVE";
export const RELEASE_CONSTITUTION_ID = "KCCC-RELEASE-CONSTITUTION";
export const V2_PLANNING_REVIEW_STATUS = "PLANNED";
export const V2_AUTHORIZATION_STATUS = "NOT_ISSUED";
export const FURTHER_TOP_LEVEL_GOVERNANCE = "ONLY_IF_CONCRETE_GAP";
export const ENGINEERING_AUDIT_STATUS = "ACTIVE";
export const AUDIT_CONSTITUTION_STATUS = "ACTIVE";
export const AUDIT_CONSTITUTION_ID = "KCCC-AUDIT-CONSTITUTION";
export const PROTECTED_ASSETS_REGISTER_STATUS = "LIVING";
export const ENGINEERING_MATURITY_ARCHITECTURE = 4;
export const ENGINEERING_MATURITY_OPERATOR_EXPERIENCE = 2;
export const ENGINEERING_MATURITY_VISUAL_EXPERIENCE = 2;
export const ENGINEERING_MATURITY_ENGINEERING_QUALITY = 3;
export const ENGINEERING_MATURITY_PLATFORM_READINESS = 2;
export const ENGINEERING_AUDIT_NEXT_STREAM = "EA-10";
export const EA4_STATUS = "COMPLETE";
export const EA4_ASSESSMENT = "PASS";
export const EA1_STATUS = "COMPLETE";
export const EA1_ASSESSMENT = "PASS_WITH_FINDINGS";
export const EA1_ARCHITECTURE_FITNESS = "7.9/10";
export const EA1_EXECUTIVE_ACCEPTANCE = "ACCEPTED";
export const EA2_STATUS = "COMPLETE";
export const EA2_ASSESSMENT = "PASS_WITH_FINDINGS";
export const EA2_FOCUS = "DECISION_MAKING";
export const EA2_PORTFOLIO_SCORE = "6.4/10";
export const EA3_STATUS = "COMPLETE";
export const EA3_ASSESSMENT = "PASS_WITH_FINDINGS";
export const EA3_EXECUTIVE_ACCEPTANCE = "ACCEPTED";
export const EA3_FOCUS = "PLATFORM_QUALITY";
export const PLATFORM_QUALITY_SCORE = "5.7/10";
export const ENGINEERING_SUSTAINABILITY_INDEX = "5.7/10";
export const ESI_TRACKING = true;
export const EA5_STATUS = "COMPLETE";
export const EA5_ASSESSMENT = "PASS_WITH_FINDINGS";
export const EA5_EXECUTIVE_ACCEPTANCE = "ACCEPTED";
export const EA5_FOCUS = "INCLUSIVE_EXPERIENCE";
export const EA5_FIRST_EXECUTION_AUDIT = true;
export const EA6_STATUS = "COMPLETE";
export const EA6_ASSESSMENT = "PASS_WITH_FINDINGS";
export const EA6_EXECUTIVE_ACCEPTANCE = "ACCEPTED";
export const EA6_MEASURE_ONLY = true;
export const EA7_STATUS = "COMPLETE";
export const EA7_ASSESSMENT = "PASS_WITH_FINDINGS";
export const EA7_EXECUTIVE_ACCEPTANCE = "ACCEPTED";
export const EA8_STATUS = "COMPLETE";
export const EA8_ASSESSMENT = "PASS_WITH_FINDINGS";
export const EA8_EXECUTIVE_ACCEPTANCE = "ACCEPTED";
export const EA9_STATUS = "COMPLETE";
export const EA9_ASSESSMENT = "PASS_WITH_FINDINGS";
export const EA10_STATUS = "OPENED";
export const HARDENING_LEDGER_THROUGH = "HL-045";
export const V1_PRODUCT_HEALTH_STATUS = "COMPLETE";
export const V1_PRODUCT_HEALTH_ASSESSMENT = "PASS_WITH_FINDINGS";
export const NEVER_FAKE_DOCTRINE_STATUS = "ACTIVE";
export const OPERATOR_CONFIDENCE_INDEX_TRACKING = true;
export const ENGINEERING_PATTERNS_STATUS = "ACTIVE";
export const HARDENING_MASTER_LEDGER_STATUS = "SEEDED";
export const HARDENING_WAVES_DEFINED = true;
export const HARDENING_WAVE_COUNT = 6;
export const PROGRAM_READINESS_REVIEW_STATUS = "PLANNED";
export const ARCHITECTURE_FITNESS_HARDENING_TARGET = "8.8+";
export const ARCHITECTURE_FITNESS_V2_MAINTAIN = "9.0+";
export const DECISION_PORTFOLIO_REDESIGN_TARGET = "8.0+";
export const ESI_HARDENING_TARGET = "7.5+";
export const ESI_FOUNDATION_TARGET = "8.5+";
export const ESI_V2_MAINTAIN = "8.5+";
export const V2_SUCCESS_TARGET_ALL_METRICS = "9.0+";
export const HARDENING_PASS_STATUS = "BLOCKED";
export const HARDENING_BLOCKED_UNTIL = "PROGRAM_READINESS_REVIEW";
export const EXPERIENCE_REDESIGN_STATUS = "PROPOSED";
export const EXPERIENCE_REDESIGN_VISION_STATUS = "CAPTURED";
export const EXPERIENCE_REDESIGN_IMPLEMENTATION = "BLOCKED";
export const EXPERIENCE_REDESIGN_FIRST_DELIVERABLE = "XR-01-EXECUTIVE-HERO-LAYER";
export const EXPERIENCE_REDESIGN_AI_MODE = "CONTEXTUAL_NOT_CONVERSATIONAL";
export const CALENDAR_FOUNDATION_STATUS = "V1_BUILD_COMPLETE_OBSERVATION_OPEN";
export const NEXT_ARCHITECTURAL_DELIVERABLE = "KCCC_PHASE3_TRUST_MODEL";
export const NEXT_ENGINEERING_DELIVERABLE = "KCCC-EA-10-TECHNICAL-DEBT";
export const CONSTITUTION_ID = "KCCC_CONSTITUTION_v1.0";
export const GOVERNANCE_STATE_ID = "KCCC_GOVERNANCE_STATE_v1.0";
export const ARCHITECTURE_FREEZE_ID = "KCCC_ARCHITECTURE_FREEZE_v1.0";
export const ARCHITECTURE_REGISTER_ID = "KCCC_ARCHITECTURE_REGISTER_v1.0";
export const FINAL_ARCHIVAL_STATE_ID = "KCCC_ARCHITECTURE_1.0_FINAL_ARCHIVAL_STATE";
export const APPLICATION_VERSION = "0.8.4-petition";
export const ARCHITECTURE_REGISTER_COMMIT = "6690ce2";
export const ARCHITECTURE_ARCHIVE_SEAL_COMMIT = "4252827";
export const ARCHITECTURE_TERMINAL_RECORD_TIP = "a64eef3";
export const ARCHITECTURE_ENGINEERING_LINE_AT_CLOSE = "cdb5a5f";
export const ARCHITECTURE_ARCHIVE_COMPLETE = true;
export const ARCHITECTURE_ACTIVE_DESIGN_PROGRAM = false;
export const ARCHITECTURE_PERMANENTLY_CLOSED = true;
export const PHASE_1_STATUS = "CERTIFIED";
export const PHASE_1_VERSION = "0.7.11-ops";
export const PHASE_2_STATUS = "CERTIFIED";
export const PHASE_2_VERSION = "0.8.4-petition";
export const PHASE_3_STATUS = "ARCHITECTURE_REVIEW";
export const PHASE_3_TITLE = "Trusted Connected Platform";
export const PHASE_3_SCRIPT_ID = "KCCC-PHASE-03-TRUSTED-CONNECTED-PLATFORM";
export const TOTAL_STEPS = 25;
export const PRODUCT_CODE = "KCCC";
export const SERVICE_NAME = "kelly-campaign-command-calendar";
export const HISTORICAL_IMPORT_FLOOR = "2025-11-01";
