import type { EventMissionSource } from "@/lib/missions/v21/types";

/**
 * Synthetic seed sources for V2.1 preview / validation.
 * No real PII. Incomplete example proves draft-valid projection.
 */
export const MISSION_V21_SEED_SOURCES: EventMissionSource[] = [
  {
    id: "seed_evt_cave_city_watermelon",
    eventNumber: "KCCC-SEED-2401",
    version: 1,
    internalTitle: "Cave City Watermelon Festival",
    campaignDisplayTitle: "Cave City Watermelon Festival",
    eventType: "Festival Appearance",
    eventSubtype: null,
    status: "CONFIRMED",
    priority: "A",
    startsAt: "2026-07-24T15:00:00.000Z",
    endsAt: "2026-07-24T19:00:00.000Z",
    timezone: "America/Chicago",
    city: "Cave City",
    countyName: "Sharp",
    regionName: "Northeast",
    venueName: "Downtown Cave City",
    expectedAttendance: 400,
    candidateRole: "Greeter",
    objectives: [
      {
        isPrimary: true,
        objectiveType: "MEET_VOTERS",
        description: "Increase name recognition in Sharp County",
        successDefinition:
          "Meet Mayor\nVisit Chamber booth\nInterview with local media\nRecruit 15 volunteers\nCollect 40 supporter contacts",
        targetAudience: "Sharp County voters and community leaders",
        desiredOutcome: "Visible presence and measurable local contacts",
        priority: "A",
      },
    ],
    organizations: [
      {
        name: "Cave City Chamber of Commerce",
        organizationType: "chamber",
        role: "HOST",
      },
      {
        name: "Sharp County Republican Women",
        organizationType: "organization",
        role: "PARTNER",
      },
    ],
    people: [
      {
        displayName: "Mayor (placeholder)",
        role: "ELECTED_OFFICIAL",
        title: "Mayor",
      },
      {
        displayName: "Local reporter (placeholder)",
        role: "MEDIA",
        title: "Reporter",
      },
    ],
    followupCount: 0,
    hasOutcome: false,
    travelRequired: true,
  },
  {
    id: "seed_evt_incomplete_draft",
    eventNumber: "KCCC-SEED-2402",
    version: 1,
    internalTitle: "County stop — details TBD",
    campaignDisplayTitle: "County stop — details TBD",
    eventType: null,
    eventSubtype: null,
    status: "DRAFT",
    priority: "Normal",
    startsAt: "2026-08-02T17:00:00.000Z",
    endsAt: "2026-08-02T18:00:00.000Z",
    timezone: "America/Chicago",
    city: null,
    countyName: null,
    regionName: null,
    venueName: null,
    expectedAttendance: null,
    candidateRole: null,
    objectives: [],
    organizations: [],
    people: [],
    followupCount: 0,
    hasOutcome: false,
    travelRequired: false,
  },
  {
    id: "seed_evt_fundraiser_ready",
    eventNumber: "KCCC-SEED-2403",
    version: 2,
    internalTitle: "River Valley Reception",
    campaignDisplayTitle: "River Valley Reception",
    eventType: "Fundraiser",
    eventSubtype: "Reception",
    status: "APPROVED",
    priority: "A",
    startsAt: "2026-08-10T23:00:00.000Z",
    endsAt: "2026-08-11T01:30:00.000Z",
    timezone: "America/Chicago",
    city: "Fort Smith",
    countyName: "Sebastian",
    regionName: "West",
    venueName: "Private residence (city only)",
    expectedAttendance: 80,
    candidateRole: "Speaker",
    objectives: [
      {
        isPrimary: true,
        objectiveType: "RAISE_MONEY",
        description: "Raise support among River Valley donors",
        successDefinition: "Confirm host thank-you; capture 12 new donor contacts",
        targetAudience: "Republican women; educators; veterans",
        desiredOutcome: "Strengthen Sebastian County fundraising network",
        priority: "A",
      },
    ],
    organizations: [
      {
        name: "River Valley Business Alliance",
        organizationType: "business",
        role: "HOST",
      },
    ],
    people: [
      { displayName: "Host (placeholder)", role: "DONOR", title: "Host" },
      {
        displayName: "Volunteer captain (placeholder)",
        role: "VOLUNTEER",
        title: "Captain",
      },
    ],
    followupCount: 2,
    hasOutcome: false,
    travelRequired: true,
  },
];
