import { addDaysToDateKey, classifyLogisticsDay, formatCampaignTime, formatFullCampaignDate } from "@/lib/missions/v21/logistics-pack/logistics-date";
import { labelLogisticsPackStatus, labelLogisticsReadiness } from "@/lib/missions/v21/logistics-pack/labels";
import { deriveLogisticsReadiness, evaluateLogisticsFindings, scheduleFingerprint, travelFingerprint } from "@/lib/missions/v21/logistics-pack/readiness";
import { DEFAULT_LOGISTICS_PACK_CONFIG, type LogisticsPackConfig } from "@/lib/missions/v21/logistics-pack/logistics-config";
import type { DayLogisticsBoardView, LogisticsMissionContext, MissionLogisticsPackPersisted, MissionLogisticsWorkspaceView } from "@/lib/missions/v21/logistics-pack/types";
import { selectTodaysMission } from "@/lib/missions/v21/select-todays-mission";

export function buildMissionLogisticsWorkspaceView(input: { context: LogisticsMissionContext; pack: MissionLogisticsPackPersisted | null; config?: LogisticsPackConfig }): MissionLogisticsWorkspaceView {
  const config = input.config ?? DEFAULT_LOGISTICS_PACK_CONFIG; const { context: ctx, pack } = input;
  const findings = evaluateLogisticsFindings({ context: ctx, pack, config }); const derived = deriveLogisticsReadiness({ context: ctx, pack, findings });
  return { mission: { missionId: ctx.missionId, title: ctx.title, whenLabel: `${formatCampaignTime(ctx.startsAt, ctx.timezone, { includeDate: true })} – ${formatCampaignTime(ctx.endsAt, ctx.timezone)}`, locationLabel: ctx.locationLabel, campaignDateKey: ctx.campaignDateKey, lifecyclePhase: ctx.lifecyclePhase, operationalStatus: ctx.operationalStatus, materialsIndicated: ctx.materialsIndicated, isCancelled: ctx.isCancelled, href: `/system/missions/${ctx.missionId}`, prepareHref: `/system/missions/${ctx.missionId}/prepare`, executeHref: `/system/missions/${ctx.missionId}/execute` }, pack: { exists: Boolean(pack), id: pack?.id ?? null, status: pack?.status ?? "DRAFT", statusLabel: labelLogisticsPackStatus(pack?.status ?? "DRAFT"), readinessState: pack?.readinessState ?? "NOT_ASSESSED", readinessStateLabel: labelLogisticsReadiness(pack?.readinessState ?? "NOT_ASSESSED"), derivedReadiness: derived, derivedReadinessLabel: labelLogisticsReadiness(derived), logisticsRequired: pack?.logisticsRequired ?? null, label: pack?.label ?? null, packOwnerName: pack?.packOwnerName ?? null, packOwnerUserId: pack?.packOwnerUserId ?? null, assemblyLocation: pack?.assemblyLocation ?? null, plannedHandoffAt: pack?.plannedHandoffAt ?? null, plannedHandoffLocation: pack?.plannedHandoffLocation ?? null, relatedTravelPlanId: pack?.relatedTravelPlanId ?? null, acceptedRiskSummary: pack?.acceptedRiskSummary ?? null, internalNotes: pack?.internalNotes ?? null, logisticsNotes: pack?.logisticsNotes ?? null, scheduleFingerprint: pack?.scheduleFingerprint ?? null, travelFingerprint: pack?.travelFingerprint ?? null, confirmedAt: pack?.confirmedAt ?? null, expectedUpdatedAt: pack?.updatedAt ?? null, items: pack?.items ?? [], handoffs: pack?.handoffs ?? [], acknowledgements: pack?.acknowledgements ?? [] }, findings, blockerCount: findings.filter((f) => f.severity === "BLOCKER" && !f.clearsForReadiness).length, warningCount: findings.filter((f) => f.severity === "WARNING" && !f.clearsForReadiness).length, boundaryMessage: "Logistics Pack status does not start or complete the Mission. Editing logistics does not change Event schedule, Prepare, Execute, Debrief, Follow-up, Closeout, or Morning Launch Review state.", isolation: { mutatesMissionLifecycle: false, mutatesEventSchedule: false, startsExecution: false } };
}

export function buildDayLogisticsBoardView(input: { campaignDate: string; now: Date; campaignTimezone: string; missions: LogisticsMissionContext[]; packsByMissionId: Map<string, MissionLogisticsPackPersisted>; config?: LogisticsPackConfig }): DayLogisticsBoardView {
  const config = input.config ?? DEFAULT_LOGISTICS_PACK_CONFIG; const { campaignDate: dateKey, campaignTimezone: tz } = input; const day = classifyLogisticsDay(dateKey, input.now, tz);
  const sorted = [...input.missions].sort((a, b) => a.startsAt.localeCompare(b.startsAt) || a.missionId.localeCompare(b.missionId)); const firstId = sorted[0]?.missionId ?? null;
  const primaryId = selectTodaysMission(sorted.map((m) => ({ id: m.missionId, startsAt: m.startsAt, endsAt: m.endsAt, lifecyclePhase: m.lifecyclePhase as never })), { now: input.now, timezone: tz }).primaryId;
  const missions = sorted.map((m) => { const pack = input.packsByMissionId.get(m.missionId) ?? null; const findings = evaluateLogisticsFindings({ context: m, pack, config }); const readiness = deriveLogisticsReadiness({ context: m, pack, findings }); return { missionId: m.missionId, title: m.title, whenLabel: formatCampaignTime(m.startsAt, tz, { includeDate: false }), locationLabel: m.locationLabel, isFirst: m.missionId === firstId, isPrimary: m.missionId === primaryId, isCancelled: m.isCancelled, packExists: Boolean(pack && !["INACTIVE", "CANCELLED"].includes(pack.status)), packStatus: pack?.status ?? null, readiness, readinessLabel: labelLogisticsReadiness(readiness), itemCount: pack?.items.filter((item) => !["CANCELLED", "NOT_APPLICABLE"].includes(item.status)).length ?? 0, blockerCount: findings.filter((f) => f.severity === "BLOCKER" && !f.clearsForReadiness).length, warningCount: findings.filter((f) => f.severity === "WARNING" && !f.clearsForReadiness).length, findings: findings.slice(0, config.sectionLimits.findings), href: `/system/missions/${m.missionId}/logistics` }; });
  const withPackCount = missions.filter((m) => m.packExists).length; const prev = addDaysToDateKey(dateKey, -1); const next = addDaysToDateKey(dateKey, 1);
  return { campaignDate: dateKey, dateLabel: formatFullCampaignDate(dateKey, tz), timezone: tz, generatedAt: input.now.toISOString(), ...day, summary: { missionCount: missions.length, withPackCount, withoutPackCount: missions.length - withPackCount, blockerCount: missions.reduce((n, m) => n + m.blockerCount, 0), warningCount: missions.reduce((n, m) => n + m.warningCount, 0), firstMissionTitle: missions.find((m) => m.isFirst)?.title ?? null, primaryMissionTitle: missions.find((m) => m.isPrimary)?.title ?? null }, missions: missions.slice(0, config.sectionLimits.dayMissions), navigation: { todayHref: "/system/briefing/logistics", briefingHref: `/system/briefing/${dateKey}`, launchHref: `/system/briefing/${dateKey}/launch`, closeoutHref: `/system/briefing/${dateKey}/closeout`, commandCenterHref: "/system/missions/command-center", todaysMissionHref: "/", reportHref: `/system/briefing/${dateKey}/logistics/report`, previousHref: `/system/briefing/${prev}/logistics`, nextHref: `/system/briefing/${next}/logistics` }, isolation: { mutatesMissionLifecycle: false, startsExecution: false, launchesCampaignDay: false } };
}
export { scheduleFingerprint, travelFingerprint };
