export type MissionLogisticsPackStatus = "DRAFT" | "ACTIVE" | "READY" | "NEEDS_REVIEW" | "INACTIVE" | "CANCELLED";
export type MissionLogisticsReadiness = "NOT_ASSESSED" | "READY" | "READY_WITH_ACCEPTED_RISK" | "NOT_READY" | "NOT_REQUIRED";
export type MissionLogisticsItemCategory = "DOCUMENTS" | "CREDENTIALS" | "SIGNAGE" | "PRINTED_MATERIALS" | "TECHNOLOGY" | "AUDIO_VISUAL" | "WARDROBE" | "FOOD_WATER" | "ACCESSIBILITY" | "SECURITY" | "VOLUNTEER_MATERIALS" | "GENERAL_SUPPLIES" | "OTHER";
export type MissionLogisticsItemStatus = "REQUIRED" | "ASSIGNED" | "PACKED" | "HANDED_OFF" | "RECEIVED" | "READY" | "USED" | "RETURN_PENDING" | "RETURNED" | "NOT_APPLICABLE" | "CANCELLED";
export type MissionLogisticsItemCriticality = "CRITICAL" | "STANDARD" | "OPTIONAL";
export type MissionLogisticsHandoffStatus = "PLANNED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
export type MissionLogisticsIssueType = "NO_PACK" | "CRITICAL_UNASSIGNED" | "CRITICAL_NOT_PACKED" | "DEPARTURE_NOT_READY" | "HANDOFF_INCOMPLETE" | "HANDOFF_PARTIAL_CONFIRM" | "MISSING_OWNER" | "ITEM_INCOMPLETE" | "RETURN_OUTSTANDING" | "STALE_AFTER_RESCHEDULE" | "STALE_AFTER_TRAVEL_CHANGE" | "CANCELLED_MISSION_ACTIVE_PACK" | "WRONG_CAMPAIGN_DAY" | "TIME_CONFLICT" | "OWNER_OVERLAP" | "OPERATOR_ADDED";
export type MissionLogisticsAcknowledgementDisposition = "ACKNOWLEDGED" | "ACCEPTED_RISK" | "RESOLVED" | "NOT_APPLICABLE";
export type LogisticsFindingSeverity = "BLOCKER" | "WARNING" | "INFO";

export type MissionLogisticsItemPersisted = { id: string; sequence: number; category: MissionLogisticsItemCategory; description: string; quantityLabel: string | null; responsibleName: string | null; responsibleUserId: string | null; recipientName: string | null; requiredByAt: string | null; packLocation: string | null; status: MissionLogisticsItemStatus; criticality: MissionLogisticsItemCriticality; returnRequired: boolean; notes: string | null; createdAt: string; updatedAt: string };
export type MissionLogisticsHandoffPersisted = { id: string; logisticsItemId: string | null; fromName: string | null; toName: string | null; plannedAt: string | null; plannedLocation: string | null; actualAt: string | null; actualLocation: string | null; status: MissionLogisticsHandoffStatus; giverConfirmedAt: string | null; giverConfirmedByUserId: string | null; receiverConfirmedAt: string | null; receiverConfirmedByUserId: string | null; notes: string | null; createdAt: string; updatedAt: string };
export type MissionLogisticsAcknowledgementPersisted = { id: string; issueKey: string; issueType: MissionLogisticsIssueType; title: string; disposition: MissionLogisticsAcknowledgementDisposition; note: string | null; acceptedRiskReason: string | null; acknowledgedAt: string; acknowledgedByUserId: string | null; createdAt: string; updatedAt: string };
export type MissionLogisticsPackPersisted = { id: string; missionId: string; campaignDateKey: string; label: string; status: MissionLogisticsPackStatus; readinessState: MissionLogisticsReadiness; logisticsRequired: boolean | null; packOwnerName: string | null; packOwnerUserId: string | null; assemblyLocation: string | null; plannedHandoffAt: string | null; plannedHandoffLocation: string | null; relatedTravelPlanId: string | null; acceptedRiskSummary: string | null; internalNotes: string | null; logisticsNotes: string | null; scheduleFingerprint: string | null; travelFingerprint: string | null; confirmedAt: string | null; confirmedByUserId: string | null; createdByUserId: string | null; updatedByUserId: string | null; createdAt: string; updatedAt: string; items: MissionLogisticsItemPersisted[]; handoffs: MissionLogisticsHandoffPersisted[]; acknowledgements: MissionLogisticsAcknowledgementPersisted[] };

export type LogisticsMissionContext = { missionId: string; title: string; startsAt: string; endsAt: string; timezone: string; locationLabel: string | null; campaignDateKey: string; lifecyclePhase: string; operationalStatus: string; isCancelled: boolean; materialsIndicated: boolean; travelPlannedDepartureAt: string | null };
export type LogisticsFinding = { issueKey: string; issueType: MissionLogisticsIssueType; title: string; explanation: string; severity: LogisticsFindingSeverity; severityLabel: string; missionId: string; disposition: MissionLogisticsAcknowledgementDisposition | null; clearsForReadiness: boolean };
export type MissionLogisticsWorkspaceView = { mission: { missionId: string; title: string; whenLabel: string; locationLabel: string | null; campaignDateKey: string; lifecyclePhase: string; operationalStatus: string; materialsIndicated: boolean; isCancelled: boolean; href: string; prepareHref: string; executeHref: string }; pack: { exists: boolean; id: string | null; status: MissionLogisticsPackStatus; statusLabel: string; readinessState: MissionLogisticsReadiness; readinessStateLabel: string; derivedReadiness: MissionLogisticsReadiness; derivedReadinessLabel: string; logisticsRequired: boolean | null; label: string | null; packOwnerName: string | null; packOwnerUserId: string | null; assemblyLocation: string | null; plannedHandoffAt: string | null; plannedHandoffLocation: string | null; relatedTravelPlanId: string | null; acceptedRiskSummary: string | null; internalNotes: string | null; logisticsNotes: string | null; scheduleFingerprint: string | null; travelFingerprint: string | null; confirmedAt: string | null; expectedUpdatedAt: string | null; items: MissionLogisticsItemPersisted[]; handoffs: MissionLogisticsHandoffPersisted[]; acknowledgements: MissionLogisticsAcknowledgementPersisted[] }; findings: LogisticsFinding[]; blockerCount: number; warningCount: number; boundaryMessage: string; isolation: { mutatesMissionLifecycle: false; mutatesEventSchedule: false; startsExecution: false } };
export type DayLogisticsMissionCard = { missionId: string; title: string; whenLabel: string; locationLabel: string | null; isFirst: boolean; isPrimary: boolean; isCancelled: boolean; packExists: boolean; packStatus: MissionLogisticsPackStatus | null; readiness: MissionLogisticsReadiness; readinessLabel: string; itemCount: number; blockerCount: number; warningCount: number; findings: LogisticsFinding[]; href: string };
export type DayLogisticsBoardView = { campaignDate: string; dateLabel: string; timezone: string; generatedAt: string; isToday: boolean; isPast: boolean; isFuture: boolean; summary: { missionCount: number; withPackCount: number; withoutPackCount: number; blockerCount: number; warningCount: number; firstMissionTitle: string | null; primaryMissionTitle: string | null }; missions: DayLogisticsMissionCard[]; navigation: { todayHref: string; briefingHref: string; launchHref: string; closeoutHref: string; commandCenterHref: string; todaysMissionHref: string; reportHref: string; previousHref: string | null; nextHref: string | null }; isolation: { mutatesMissionLifecycle: false; startsExecution: false; launchesCampaignDay: false } };
